//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2_Top10words.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Top10WordsService", ReplyAction="http://tempuri.org/IService1/Top10WordsServiceResponse")]
        string[] Top10WordsService(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Top10WordsService", ReplyAction="http://tempuri.org/IService1/Top10WordsServiceResponse")]
        System.Threading.Tasks.Task<string[]> Top10WordsServiceAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/readdatafromurl", ReplyAction="http://tempuri.org/IService1/readdatafromurlResponse")]
        string readdatafromurl(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/readdatafromurl", ReplyAction="http://tempuri.org/IService1/readdatafromurlResponse")]
        System.Threading.Tasks.Task<string> readdatafromurlAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/topwordsindesc", ReplyAction="http://tempuri.org/IService1/topwordsindescResponse")]
        string[] topwordsindesc(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/topwordsindesc", ReplyAction="http://tempuri.org/IService1/topwordsindescResponse")]
        System.Threading.Tasks.Task<string[]> topwordsindescAsync(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication2_Top10words.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication2_Top10words.ServiceReference1.IService1>, WebApplication2_Top10words.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] Top10WordsService(string url) {
            return base.Channel.Top10WordsService(url);
        }
        
        public System.Threading.Tasks.Task<string[]> Top10WordsServiceAsync(string url) {
            return base.Channel.Top10WordsServiceAsync(url);
        }
        
        public string readdatafromurl(string url) {
            return base.Channel.readdatafromurl(url);
        }
        
        public System.Threading.Tasks.Task<string> readdatafromurlAsync(string url) {
            return base.Channel.readdatafromurlAsync(url);
        }
        
        public string[] topwordsindesc(string text) {
            return base.Channel.topwordsindesc(text);
        }
        
        public System.Threading.Tasks.Task<string[]> topwordsindescAsync(string text) {
            return base.Channel.topwordsindescAsync(text);
        }
    }
}
